version: "3.3"

networks:
  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  consul:
    image: "consul"
    restart: "always"
    networks:
      - back-tier
    ports:
      - "0.0.0.0:8500:8500"
      - "172.28.0.1:53:8600/udp"

  consul-registrator:
    image: "gliderlabs/registrator"
    restart: "always"
    network_mode: "service:consul"
    command: consul://localhost:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  vault:
    image: "vault"
    restart: "always"
    volumes:
      - ./vault/file:/vault/file:rw
    networks:
      - back-tier
    ports:
      - "0.0.0.0:8200:8200"
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: >-
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
               "address": "0.0.0.0:8200",
               "tls_disable": 1
            }
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }

  vault-ui:
    image: "djenriquez/vault-ui"
    networks:
      - back-tier
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      VAULT_URL_DEFAULT: "http://vault.service.consul:8200"
    dns: 172.28.0.1
    dns_search:
      - service.consul
