version: "3.3"

networks:
  front-tier:
  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  consul:
    image: "consul"
    restart: "always"
    networks:
      back-tier:
        ipv4_address: 172.28.0.2
    ports:
      - "8500:8500"
      - "172.28.0.1:53:8600/udp"
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "datacenter": "tools",
          "data_dir": "/consul/data",
          "server": true,
          "bootstrap": true,
          "bind_addr": "172.28.0.2",
          "client_addr": "0.0.0.0",
          "enable_script_checks": true,
          "ui": true,
          "acl_datacenter":"tools",
          "acl_default_policy":"allow",
          "acl_down_policy":"allow",
          "acl_master_token":"398073a8-5091-4d9c-871a-bbbeb030d1f6"
        }

  consul-registrator:
    image: "gliderlabs/registrator"
    restart: "always"
    networks:
      - back-tier
    command: consul://172.28.0.1:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  vault:
    image: "vault"
    restart: "always"
    volumes:
      - ./vault/file:/vault/file:rw
    networks:
      - back-tier
    ports:
      - "0.0.0.0:8200:8200"
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: >-
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
               "address": "0.0.0.0:8200",
               "tls_disable": 1
            }
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }

  vault-ui:
    image: "djenriquez/vault-ui"
    networks:
      - back-tier
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      VAULT_URL_DEFAULT: "http://vault.service.consul:8200"
    dns: 172.28.0.1
    dns_search:
      - service.consul
