version: "3.3"

networks:
  backtier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  consul:
    image: "consul"
    container_name: "consul"
    hostname: "${CONSUL_NODENAME}"
    restart: "always"
    volumes:
      - ./consul/data:/consul/data:rw
      - ./consul/config:/consul/config:rw
    network_mode: host
    privileged: true
    # networks:
    #   backtier:
    #     ipv4_address: 172.28.0.2
    # ports:
    #   - "8300:8300/tcp"
    #   - "8400:8400/tcp"
    #   - "8301:8301/udp"
    #   - "8302:8302/tcp"
    #   - "8500:8500/tcp"
    #   - "53:8600/udp"
    command: "agent"
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS:
      CONSUL_LOCAL_CONFIG: >-
        {
          "ui": true,
          "server": true,
          "datacenter": "tools",
          "data_dir": "/consul/data",
          "bind_addr": "0.0.0.0",
          "advertise_addr": "${HOSTIP}",
          "client_addr": "0.0.0.0",
          "enable_script_checks": true,
          "acl_datacenter":"tools",
          "acl_default_policy":"allow",
          "acl_down_policy":"allow",
          "acl_master_token":"398073a8-5091-4d9c-871a-bbbeb030d1f6",
          "rejoin_after_leave": true,
          "bootstrap_expect": 3,
          "ports": {
            "dns": 53
          }
        }

  consul-registrator:
    image: "gliderlabs/registrator"
    container_name: "consul-registrator"
    restart: "always"
    # networks:
    #   backtier:
    #     ipv4_address: 172.28.0.3
    network_mode: host
    command: consul://172.28.0.1:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  vault:
    image: "vault"
    container_name: "vault"
    restart: "always"
    volumes:
      - ./vault/file:/vault/file:rw
    networks:
      backtier:
        ipv4_address: 172.28.0.4
    ports:
      - "0.0.0.0:8200:8200"
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: >-
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
               "address": "0.0.0.0:8200",
               "tls_disable": 1
            }
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    depends_on:
      - consul

  vault-ui:
    image: "djenriquez/vault-ui"
    container_name: "vault-ui"
    networks:
      backtier:
        ipv4_address: 172.28.0.5
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      VAULT_URL_DEFAULT: "http://vault.service.consul:8200"
    # dns: 172.28.0.1
    # dns_search:
    #   - service.consul
    depends_on:
      - vault
